version: '3.8'
services:
  api:
    build: .
    container_name: primetrade_api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/primetrade_api
      - JWT_ACCESS_SECRET=change_me_access
      - JWT_REFRESH_SECRET=change_me_refresh
      - CORS_ORIGIN=*
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE=http://api:4000/api/v1
    container_name: primetrade_frontend
    ports:
      - "8080:80"
    depends_on:
      - api
  mongo:
    image: mongo:7
    container_name: primetrade_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:


